### ISSUE TITLE
Survival analysis

### ISSUE THREAD

**Issue by BardiaYou** [hsieh42/ctDNA#1]
Hi Michael,
I have a problem with using lifelines.CoxPHFitter(), I read a CSV file from "[here](https://drive.google.com/open?id=1bjoCiZuKovJVO7cpFc8booq8o5PwOvZe)" and then I want to fit function to perform the reset of survival analysis. It does not work ([Here is my Jupiter Notebook](https://drive.google.com/open?id=1C5T65nm4Knmzu0EnJpC7DT1Lg4vhCYbV)).

Thank you!

**Comment by hsieh42** [comment]
```python
cph = lifelines.CoxPHFitter()
cph.fit(df_merge2 , duration_col = 'Elongation', event_col = '429Survival Status', show_progress = True)
cph.print_summary()
```
You are asking the cph to use the `Elongation` as the duration column and `429Survival Status` as the column for event coding. But your df_merge2, display in the next cell, has features as rows and datapoints in columns (transposed). Therefore it was not able to find `Elongation` in the columns. You gotta read the csv correctly, where columns are features and rows are datapoints.

**Comment by BardiaYou** [comment]
The problem of reading columns and CSV file is temporarily solved. Thanks!
I am facing another issue for fitting cph. I changed the [Data](https://drive.google.com/open?id=19-GcR5cU7RQcFNaDUmHOiPVqaSSndiE9) and [code](https://drive.google.com/open?id=1y_DlE_UsrmwghFwCDjnJKXjSZM4eOoye). 
Two errors happened:
1. Once it trying to fit gives me: _ValueError: Unable to coerce to Series, length must be 444: given 428_
There is no 444 as the size of the input matrix is 429.

2. Once I'm changing the column to 'MinorAxis', it gives me this: _error: ValueError: delta contains nan value(s)._ 
then I check the column and seeing there is no NAN value:
f = dff.T['MinorAxis']
f.isnull().values.any()

Could you give any suggestion, thank you!
